module Import
    (Reactjs : Caelm.Reactjs.S)
    (Base : module type of Base.Make (Reactjs)) =
struct
  module Html = struct
    open Base.Html

    type +'a elt = 'a Base.Html.elt
    type +'a attrib = 'a Base.Html.attrib

    module Unsafe = struct
      include Unsafe

      let bool_attrib name value = Base.Xml.bool_attrib name value |> to_attrib

      let event_handler_attrib = Base.Html.event_handler_attrib

      let object_attrib = Base.Html.object_attrib

      let react_component constr ?(props=[]) children =
        let props = to_xmlattribs props in
        Base.Xml.react_component constr ~props (toeltl children) |> tot
    end

    let a_key = a_key
    let a_dangerouslysetinnerhtml = a_dangerouslysetinnerhtml

    let a_user_data = a_user_data

    let a_accept = a_accept
    let a_accept_charset = a_accept_charset
    let a_accesskey = a_accesskey
    let a_action = a_action
    let a_alt = a_alt
    let a_async = a_async
    let a_autocomplete = a_autocomplete
    let a_autofocus = a_autofocus
    let a_autoplay = a_autoplay
    let a_button_type = a_button_type
    let a_charset = a_charset
    let a_challenge = a_challenge
    let a_checked = a_checked
    let a_cite = a_cite
    let a_class = a_class
    let a_cols = a_cols
    let a_colspan = a_colspan
    let a_content = a_content
    let a_contenteditable = a_contenteditable
    let a_contextmenu = a_contextmenu
    let a_controls = a_controls
    let a_coords = a_coords
    let a_crossorigin = a_crossorigin
    let a_data = a_data
    let a_datetime = a_datetime
    let a_defer = a_defer
    let a_dir = a_dir
    let a_disabled = a_disabled
    let a_download = a_download
    let a_draggable = a_draggable
    let a_enctype = a_enctype
    let a_form = a_form
    let a_formaction = a_formaction
    let a_formenctype = a_formenctype
    let a_formnovalidate = a_formnovalidate
    let a_formtarget = a_formtarget
    let a_headers = a_headers
    let a_height = a_height
    let a_hidden = a_hidden
    let a_high = a_high
    let a_href = a_href
    let a_hreflang = a_hreflang
    let a_http_equiv = a_http_equiv
    let a_id = a_id
    let a_input_type = a_input_type
    let a_inputmode = a_inputmode
    let a_keytype = a_keytype
    let a_label = a_label
    let a_label_for = a_label_for
    let a_lang = a_lang
    let a_list = a_list
    let a_loop = a_loop
    let a_low = a_low
    let a_manifest = a_manifest
    let a_max = a_max
    let a_maxlength = a_maxlength
    let a_media = a_media
    let a_mediagroup = a_mediagroup
    let a_method = a_method
    let a_mime_type = a_mime_type
    let a_min = a_min
    let a_multiple = a_multiple
    let a_muted = a_muted
    let a_name = a_name
    let a_novalidate = a_novalidate
    let a_open = a_open
    let a_optimum = a_optimum
    let a_pattern = a_pattern
    let a_placeholder = a_placeholder
    let a_poster = a_poster
    let a_preload = a_preload
    let a_property = a_property
    let a_radiogroup = a_radiogroup
    let a_readonly = a_readonly
    let a_rel = a_rel
    let a_required = a_required
    let a_reversed = a_reversed
    let a_rows = a_rows
    let a_rowspan = a_rowspan
    let a_sandbox = a_sandbox
    let a_scoped = a_scoped
    let a_scrolling = a_scrolling
    let a_seamless = a_seamless
    let a_selected = a_selected
    let a_shape = a_shape
    let a_size = a_size
    let a_sizes = a_sizes
    let a_span = a_span
    let a_spellcheck = a_spellcheck
    let a_src = a_src
    let a_srcset = a_srcset
    let a_start = a_start
    let a_step = a_step
    let a_style = a_style
    let a_tabindex = a_tabindex
    let a_target = a_target
    let a_title = a_title
    let a_usemap = a_usemap
    let a_value = a_value
    let a_width = a_width
    let a_wrap = a_wrap

    let a_onanimationend = a_onanimationend
    let a_onanimationiteration = a_onanimationiteration
    let a_onanimationstart = a_onanimationstart
    let a_oncopy = a_oncopy
    let a_oncut = a_oncut
    let a_onpaste = a_onpaste
    let a_oncompositionend = a_oncompositionend
    let a_oncompositionstart = a_oncompositionstart
    let a_oncompositionupdate = a_oncompositionupdate
    let a_onblur = a_onblur
    let a_onfocus = a_onfocus
    let a_onchange = a_onchange
    let a_oninput = a_oninput
    let a_onsubmit = a_onsubmit
    let a_onload = a_onload
    let a_onkeydown = a_onkeydown
    let a_onkeypress = a_onkeypress
    let a_onkeyup = a_onkeyup
    let a_onabort = a_onabort
    let a_oncanplay = a_oncanplay
    let a_oncanplaythrough = a_oncanplaythrough
    let a_ondurationchange = a_ondurationchange
    let a_onemptied = a_onemptied
    let a_onencrypted = a_onencrypted
    let a_onended = a_onended
    let a_onerror = a_onerror
    let a_onloadeddata = a_onloadeddata
    let a_onloadedmetadata = a_onloadedmetadata
    let a_onloadstart = a_onloadstart
    let a_onpause = a_onpause
    let a_onplay = a_onplay
    let a_onplaying = a_onplaying
    let a_onprogress = a_onprogress
    let a_onratechange = a_onratechange
    let a_onseeked = a_onseeked
    let a_onseeking = a_onseeking
    let a_onstalled = a_onstalled
    let a_onsuspend = a_onsuspend
    let a_ontimeupdate = a_ontimeupdate
    let a_onvolumechange = a_onvolumechange
    let a_onwaiting = a_onwaiting
    let a_onclick = a_onclick
    let a_oncontextmenu = a_oncontextmenu
    let a_ondoubleclick = a_ondoubleclick
    let a_ondrag = a_ondrag
    let a_ondragend = a_ondragend
    let a_ondragenter = a_ondragenter
    let a_ondragexit = a_ondragexit
    let a_ondragleave = a_ondragleave
    let a_ondragover = a_ondragover
    let a_ondragstart = a_ondragstart
    let a_ondrop = a_ondrop
    let a_onmousedown = a_onmousedown
    let a_onmouseenter = a_onmouseenter
    let a_onmouseleave = a_onmouseleave
    let a_onmousemove = a_onmousemove
    let a_onmouseout = a_onmouseout
    let a_onmouseover = a_onmouseover
    let a_onmouseup = a_onmouseup
    let a_onselect = a_onselect
    let a_ontouchcancel = a_ontouchcancel
    let a_ontouchend = a_ontouchend
    let a_ontouchmove = a_ontouchmove
    let a_ontouchstart = a_ontouchstart
    let a_ontransitionend = a_ontransitionend
    let a_onscroll = a_onscroll
    let a_onwheel = a_onwheel

    let html = html
    let head = head
    let base = base
    let title = title
    let body = body
    (* let svg = svg *)
    let footer = footer
    let header = header
    let section = section
    let nav = nav
    let h1 = h1
    let h2 = h2
    let h3 = h3
    let h4 = h4
    let h5 = h5
    let h6 = h6
    let hgroup = hgroup
    let address = address
    let article = article
    let aside = aside
    let main = main
    let p = p
    let pre = pre
    let blockquote = blockquote
    let div = div
    let dl = dl
    let ol = ol
    let ul = ul
    let dd = dd
    let dt = dt
    let li = li
    let figcaption = figcaption
    let figure = figure
    let hr = hr
    let b = b
    let i = i
    let u = u
    let small = small
    let sub = sub
    let sup = sup
    let mark = mark
    let wbr = wbr
    let bdo = bdo
    let abbr = abbr
    let br = br
    let cite = cite
    let code = code
    let dfn = dfn
    let em = em
    let kbd = kbd
    let q = q
    let samp = samp
    let span = span
    let strong = strong
    let time = time
    let var = var
    let a = a
    let del = del
    let ins = ins
    let img = img
    let iframe = iframe
    let object_ = object_
    let param = param
    let embed = embed
    let audio = audio
    let video = video
    let canvas = canvas
    let source = source
    let area = area
    let map = map
    let caption = caption
    let table = table
    let tablex = tablex
    let colgroup = colgroup
    let col = col
    let thead = thead
    let tbody = tbody
    let tfoot = tfoot
    let td = td
    let th = th
    let tr = tr
    let form = form
    let fieldset = fieldset
    let legend = legend
    let label = label
    let input = input
    let button = button
    let select = select
    let datalist = datalist
    let optgroup = optgroup
    let option = option
    let textarea = textarea
    let keygen = keygen
    let progress = progress
    let meter = meter
    let output_elt = output_elt
    let details = details
    let summary = summary
    let command = command
    let menu = menu
    let script = script
    let noscript = noscript
    let meta = meta
    let style = style
    let link = link
    let rt = rt
    let rp = rp
    let ruby = ruby

    let pcdata = pcdata

    let to_react_element = to_react_element
  end
end

module Make (Reactjs : Caelm.Reactjs.S) = struct
  include Import (Reactjs) (Base.Make(Reactjs))
end
